# Install python in the container
FROM python:3.10.5-alpine3.16
WORKDIR /usr/src/app

# Copy requirements and install dependencies
COPY requirements.txt ./
RUN pip install -r requirements.txt

# Expose the port that uvicorn will run the app
EXPOSE 8081

# Copy the local app folder to the container
COPY . .

# Execute the command python app.py to start the app
CMD ["python", "app.py"]