spring:
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:password123}

# JWT Configuration (must match user service)
jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-change-in-production}
  expiration: ${JWT_EXPIRATION:1800000}

# Server configuration
server:
  port: ${SERVER_PORT:8080}

# External services
services:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:9090}