apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service-gitops
  namespace: argocd
  labels:
    app: user-service
    methodology: gitops
    pipeline-type: argocd
    research-phase: phase3-gitops
    managed-by: argocd
    gitops.research/automation-level: "100"
    gitops.research/rollback-enabled: "true"
spec:
  project: default
  source:
    repoURL: 'https://github.com/kousaila502/ecommerce-microservices-platform.git'
    targetRevision: gitops-argocd
    path: gitops/user-service
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - Replace=true
  revisionHistoryLimit: 10