apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service-app
  namespace: argocd
  labels:
    app: order-service
    methodology: gitops
    pipeline-type: argocd
    research-phase: multicloud-gitops-research
    managed-by: argocd
    gitops.research/automation-level: "100"
    gitops.research/rollback-enabled: "true"
spec:
  project: default
  source:
    repoURL: 'https://github.com/kousaila502/ecommerce-microservices-platform.git'
    targetRevision: multicloud-gitops-research
    path: gitops/manifests/gcp
    directory:
      recurse: true
      include: 'order-service-deployment.yaml'  # Only include order service files
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: research-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - Replace=true
  revisionHistoryLimit: 10