apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:v1
        imagePullPolicy: Never
        env:
        - name: REACT_APP_PRODUCTS_URL_BASE
          value: "http://localhost:3001/"
        - name: REACT_APP_CART_URL_BASE
          value: "http://localhost:8080/"
        - name: REACT_APP_SEARCH_URL_BASE
          value: "http://localhost:4000/"
        - name: REACT_APP_USERS_URL_BASE
          value: "http://localhost:9090/"
        - name: REACT_APP_ORDERS_URL_BASE
          value: "http://localhost:8081/"
        ports:
        - containerPort: 80
        resources:
        requests:
          cpu: "25m"
          memory: "64Mi"
        limits:
          cpu: "50m"
          memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 80
  type: ClusterIP