apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service
spec:
  strategy:                    # ← Add this section
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: kousaila/user-service:latest #user-service:v1
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          value: postgresql+asyncpg://admin:password123@postgresql:5432/userdb        
        - name: POSTGRES_HOST
          value: postgresql
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: userdb
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: password123
        - name: SECRET_KEY
          value: your-super-secret-jwt-key-change-in-production
        - name: ALGORITHM
          value: HS256
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: "30"
        - name: CORS_ORIGINS
          value: "http://localhost:3000,http://127.0.0.1:3000,http://127.0.0.1:50951"

        ports:
        - containerPort: 9090
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
  - port: 9090
    targetPort: 9090
  type: ClusterIP